import { library as iconLibrary } from "@fortawesome/fontawesome-svg-core";

import { faYoutube } from "@fortawesome/free-brands-svg-icons";

import {
  faBars,
  faCalendarAlt,
  faCarMechanic,
  faCarSide,
  faCheck,
  faEnvelope,
  faHashtag,
  faLock,
  faMinus,
  faPaintBrush,
  faPencilAlt,
  faPlus,
  faTachometerAlt,
  faTimes,
  faTrashAlt,
  faWrench
} from "@fortawesome/pro-regular-svg-icons";

import {
  faBars as faBarsLight,
  faCalendarAlt as faCalendarAltLight,
  faCarSide as faCarSideLight,
  faCarMechanic as faCarMechanicLight,
  faCheck as faCheckLight,
  faEnvelope as faEnvelopeLight,
  faHashtag as faHashtagLight,
  faLock as faLockLight,
  faMinus as faMinusLight,
  faPaintBrush as faPaintBrushLight,
  faPencilAlt as faPencilAltLight,
  faPlus as faPlusLight,
  faTachometerAlt as faTachometerAltLight,
  faTimes as faTimesLight,
  faTrashAlt as faTrashAltLight,
  faWrench as faWrenchLight
} from "@fortawesome/pro-light-svg-icons";

import {
  faBars as faBarsSolid,
  faCalendarAlt as faCalendarAltSolid,
  faCarMechanic as faCarMechanicSolid,
  faCarSide as faCarSideSolid,
  faCheck as faCheckSolid,
  faEnvelope as faEnvelopeSolid,
  faHashtag as faHashtagSolid,
  faLock as faLockSolid,
  faMinus as faMinusSolid,
  faPaintBrush as faPaintBrushSolid,
  faPencilAlt as faPencilAltSolid,
  faPlus as faPlusSolid,
  faTachometerAlt as faTachometerAltSolid,
  faTimes as faTimesSolid,
  faTrashAlt as faTrashAltSolid,
  faWrench as faWrenchSolid
} from "@fortawesome/pro-solid-svg-icons";

iconLibrary.add(
  faBars,
  faBarsLight,
  faBarsSolid,
  faCalendarAlt,
  faCalendarAltLight,
  faCalendarAltSolid,
  faCarMechanic,
  faCarMechanicLight,
  faCarMechanicSolid,
  faCarSide,
  faCarSideLight,
  faCarSideSolid,
  faCheck,
  faCheckLight,
  faCheckSolid,
  faEnvelope,
  faEnvelopeLight,
  faEnvelopeSolid,
  faHashtag,
  faHashtagLight,
  faHashtagSolid,
  faLock,
  faLockLight,
  faLockSolid,
  faMinus,
  faMinusLight,
  faMinusSolid,
  faPaintBrush,
  faPaintBrushLight,
  faPaintBrushSolid,
  faPencilAlt,
  faPencilAltLight,
  faPencilAltSolid,
  faPlus,
  faPlusLight,
  faPlusSolid,
  faTachometerAlt,
  faTachometerAltLight,
  faTachometerAltSolid,
  faTimes,
  faTimesLight,
  faTimesSolid,
  faTrashAlt,
  faTrashAltLight,
  faTrashAltSolid,
  faWrench,
  faWrenchLight,
  faWrenchSolid,
  faYoutube
);

export default iconLibrary;
