export const makes = [
  { value: "Acura", label: "Acura" },
  { value: "BMW", label: "BMW" },
  { value: "Buick", label: "Buick" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Dodge", label: "Dodge" },
  { value: "Ford", label: "Ford" },
  { value: "GMC", label: "GMC" },
  { value: "Honda", label: "Honda" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Mercedes", label: "Mercedes" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Ram", label: "Ram" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" }
];

export const models = [
  // Acura
  { value: "ILX", label: "ILX", filter: "Acura" },
  { value: "MDX", label: "MDX", filter: "Acura" },
  { value: "NSX", label: "NSX", filter: "Acura" },
  { value: "RLX", label: "RLX", filter: "Acura" },
  { value: "TLX", label: "TLX", filter: "Acura" },
  // BMW
  { value: "1 Series", label: "1 Series", filter: "BMW" },
  { value: "2 Series", label: "2 Series", filter: "BMW" },
  { value: "3 Series", label: "3 Series", filter: "BMW" },
  { value: "4 Series", label: "4 Series", filter: "BMW" },
  { value: "5 Series", label: "5 Series", filter: "BMW" },
  { value: "6 Series", label: "6 Series", filter: "BMW" },
  { value: "7 Series", label: "7 Series", filter: "BMW" },
  { value: "8 Series", label: "8 Series", filter: "BMW" },
  { value: "i3", label: "i3", filter: "BMW" },
  { value: "i8", label: "i8", filter: "BMW" },
  { value: "X1", label: "X1", filter: "BMW" },
  { value: "X2", label: "X2", filter: "BMW" },
  { value: "X3", label: "X3", filter: "BMW" },
  { value: "X4", label: "X4", filter: "BMW" },
  { value: "X5", label: "X5", filter: "BMW" },
  { value: "X6", label: "X6", filter: "BMW" },
  { value: "X7", label: "X7", filter: "BMW" },
  { value: "Z4", label: "Z4", filter: "BMW" },
  // Buick
  { value: "Cascada", label: "Cascada", filter: "Buick" },
  { value: "Encore", label: "Encore", filter: "Buick" },
  { value: "Envision", label: "Envision", filter: "Buick" },
  { value: "Enclave", label: "Enclave", filter: "Buick" },
  { value: "LaCrosse", label: "LaCrosse", filter: "Buick" },
  { value: "Regal", label: "Regal", filter: "Buick" },
  // Cadillac
  { value: "CT6", label: "CT6", filter: "Cadillac" },
  { value: "CTS", label: "CTS", filter: "Cadillac" },
  { value: "Escalade", label: "Escalade", filter: "Cadillac" },
  { value: "XT4 Crossover", label: "XT4 Crossover", filter: "Cadillac" },
  { value: "XT5 Crossover", label: "XT5 Crossover", filter: "Cadillac" },
  { value: "XTS", label: "XTS", filter: "Cadillac" },
  // Chevrolet
  { value: "Bolt", label: "Bolt", filter: "Chevrolet" },
  { value: "Camaro", label: "Camaro", filter: "Chevrolet" },
  { value: "Colorado", label: "Colorado", filter: "Chevrolet" },
  { value: "Corvette", label: "Corvette", filter: "Chevrolet" },
  { value: "Cruze", label: "Cruze", filter: "Chevrolet" },
  { value: "Equinox", label: "Equinox", filter: "Chevrolet" },
  { value: "Imapla", label: "Impala", filter: "Chevrolet" },
  { value: "Malibu", label: "Malibu", filter: "Chevrolet" },
  { value: "Silverado", label: "Silverado", filter: "Chevrolet" },
  { value: "Sonic", label: "Sonic", filter: "Chevrolet" },
  { value: "Spark", label: "Spark", filter: "Chevrolet" },
  { value: "Suburban", label: "Suburban", filter: "Chevrolet" },
  { value: "Tahoe", label: "Tahoe", filter: "Chevrolet" },
  { value: "Traverse", label: "Traverse", filter: "Chevrolet" },
  { value: "Trax", label: "Trax", filter: "Chevrolet" },
  { value: "Volt", label: "Volt", filter: "Chevrolet" },
  // Chrysler
  { value: "300", label: "300", filter: "Chrysler" },
  { value: "Pacifica", label: "Pacifica", filter: "Chrysler" },
  // Dodge
  { value: "Avenger", label: "Avenger", filter: "Dodge" },
  { value: "Caravan", label: "Caravan", filter: "Dodge" },
  { value: "Challenger", label: "Challenger", filter: "Dodge" },
  { value: "Charger", label: "Charger", filter: "Dodge" },
  { value: "Durango", label: "Durango", filter: "Dodge" },
  { value: "Journey", label: "Journey", filter: "Dodge" },
  // Ford
  { value: "Edge", label: "Edge", filter: "Ford" },
  { value: "Ecosport", label: "Ecosport", filter: "Ford" },
  { value: "Escape", label: "Escape", filter: "Ford" },
  { value: "Expedition", label: "Expedition", filter: "Ford" },
  { value: "Explorer", label: "Explorer", filter: "Ford" },
  { value: "F-150", label: "F-150", filter: "Ford" },
  { value: "F-250", label: "F-250", filter: "Ford" },
  { value: "F-350", label: "F-350", filter: "Ford" },
  { value: "Fiesta", label: "Fiesta", filter: "Ford" },
  { value: "Flex", label: "Flex", filter: "Ford" },
  { value: "Focus", label: "Focus", filter: "Ford" },
  { value: "Fusion", label: "Fusion", filter: "Ford" },
  { value: "Mustang", label: "Mustang", filter: "Ford" },
  { value: "Ranger", label: "Ranger", filter: "Ford" },
  { value: "Taurus", label: "Taurus", filter: "Ford" },
  // GMC
  { value: "Acadia", label: "Acadia", filter: "GMC" },
  { value: "Canyon", label: "Canyon", filter: "GMC" },
  { value: "Sierra", label: "Sierra", filter: "GMC" },
  { value: "Terrain", label: "Terrain", filter: "GMC" },
  { value: "Yukon", label: "Yukon", filter: "GMC" },
  // Honda
  { value: "Accord", label: "Accord", filter: "Honda" },
  { value: "Civic", label: "Civic", filter: "Honda" },
  { value: "Clarity", label: "Clarity", filter: "Honda" },
  { value: "CR-V", label: "CR-V", filter: "Honda" },
  { value: "Fit", label: "Fit", filter: "Honda" },
  { value: "HR-V", label: "HR-V", filter: "Honda" },
  { value: "Insight", label: "Insight", filter: "Honda" },
  { value: "Odyssey", label: "Odyssey", filter: "Honda" },
  { value: "Pilot", label: "Pilot", filter: "Honda" },
  { value: "Ridgeline", label: "Ridgeline", filter: "Honda" },
  // Infiniti
  { value: "Q50", label: "Q50", filter: "Infiniti" },
  { value: "Q60", label: "Q60", filter: "Infiniti" },
  { value: "Q70", label: "Q70", filter: "Infiniti" },
  { value: "QX30", label: "QX30", filter: "Infiniti" },
  { value: "QX50", label: "QX50", filter: "Infiniti" },
  { value: "QX60", label: "QX60", filter: "Infiniti" },
  { value: "QX80", label: "QX80", filter: "Infiniti" },
  // Jaguar
  { value: "E-Pace", label: "E-Pace", filter: "Jaguar" },
  { value: "F-Pace", label: "F-Pace", filter: "Jaguar" },
  { value: "F-Type", label: "F-Type", filter: "Jaguar" },
  { value: "XE", label: "XE", filter: "Jaguar" },
  { value: "XJ", label: "XJ", filter: "Jaguar" },
  { value: "XF", label: "XF", filter: "Jaguar" },
  // Jeep
  { value: "Cherokee", label: "Cherokee", filter: "Jeep" },
  { value: "Compass", label: "Compass", filter: "Jeep" },
  { value: "Grand Cherokee", label: "Grand Cherokee", filter: "Jeep" },
  { value: "Renegade", label: "Renegade", filter: "Jeep" },
  { value: "Wrangler", label: "Wrangler", filter: "Jeep" },
  // Kia
  { value: "Forte", label: "Forte", filter: "Kia" },
  { value: "Niro", label: "Niro", filter: "Kia" },
  { value: "Optima", label: "Optima", filter: "Kia" },
  { value: "Rio", label: "Rio", filter: "Kia" },
  { value: "Sedona", label: "Sedona", filter: "Kia" },
  { value: "Sorento", label: "Sorento", filter: "Kia" },
  { value: "Soul", label: "Soul", filter: "Kia" },
  { value: "Sportage", label: "Sportage", filter: "Kia" },
  // Lexus
  { value: "ES", label: "ES", filter: "Lexus" },
  { value: "IS", label: "IS", filter: "Lexus" },
  { value: "GS", label: "GS", filter: "Lexus" },
  { value: "GX", label: "GX", filter: "Lexus" },
  { value: "LS", label: "LS", filter: "Lexus" },
  { value: "LX", label: "LX", filter: "Lexus" },
  { value: "RX-350", label: "RX-350", filter: "Lexus" },
  { value: "RX-450", label: "RX-450", filter: "Lexus" },
  // Lincoln
  { value: "Aviator", label: "Aviator", filter: "Lincoln" },
  { value: "Continental", label: "Continental", filter: "Lincoln" },
  { value: "MKC", label: "MKC", filter: "Lincoln" },
  { value: "MKZ", label: "MKZ", filter: "Lincoln" },
  { value: "Nautilus", label: "Nautilus", filter: "Lincoln" },
  { value: "Navigator", label: "Navigator", filter: "Lincoln" },
  // Mercedes
  { value: "A-Class", label: "A-Class", filter: "Mercedes" },
  { value: "C-Class", label: "C-Class", filter: "Mercedes" },
  { value: "E-Class", label: "E-Class", filter: "Mercedes" },
  { value: "CLA", label: "CLA", filter: "Mercedes" },
  { value: "GLA", label: "GLA", filter: "Mercedes" },
  { value: "G-Class SUV", label: "G-Class SUV", filter: "Mercedes" },
  // Mitsubishi
  { value: "Eclipse", label: "Eclipse", filter: "Mitsubishi" },
  { value: "Mirage", label: "Mirage", filter: "Mitsubishi" },
  { value: "Outlander", label: "Outlander", filter: "Mitsubishi" },
  // Nissan
  { value: "370z", label: "370z", filter: "Nissan" },
  { value: "Altima", label: "Altima", filter: "Nissan" },
  { value: "Armada", label: "Armada", filter: "Nissan" },
  { value: "Frontier", label: "Frontier", filter: "Nissan" },
  { value: "G-TR", label: "G-TR", filter: "Nissan" },
  { value: "Leaf", label: "Leaf", filter: "Nissan" },
  { value: "Maxima", label: "Maxima", filter: "Nissan" },
  { value: "Murano", label: "Murano", filter: "Nissan" },
  { value: "Note", label: "Note", filter: "Nissan" },
  { value: "Pathfinder", label: "Pathfinder", filter: "Nissan" },
  { value: "Rogue", label: "Rogue", filter: "Nissan" },
  { value: "Sentra", label: "Sentra", filter: "Nissan" },
  { value: "Titan", label: "Titan", filter: "Nissan" },
  { value: "Versa", label: "Versa", filter: "Nissan" },
  // Ram
  { value: "1500", label: "1500", filter: "Ram" },
  { value: "2500", label: "2500", filter: "Ram" },
  { value: "3500", label: "3500", filter: "Ram" },
  // Tesla
  { value: "Model 3", label: "Model 3", filter: "Tesla" },
  { value: "Model S", label: "Model S", filter: "Tesla" },
  { value: "Model X", label: "Model X", filter: "Tesla" },
  // Toyota
  { value: "4Runner", label: "4Runner", filter: "Toyota" },
  { value: "Avalon", label: "Avalon", filter: "Toyota" },
  { value: "Camry", label: "Camry", filter: "Toyota" },
  { value: "C-HR", label: "C-HR", filter: "Toyota" },
  { value: "Corolla", label: "Corolla", filter: "Toyota" },
  { value: "Highlander", label: "Highlander", filter: "Toyota" },
  { value: "Land Cruiser", label: "Land Cruiser", filter: "Toyota" },
  { value: "Prius", label: "Prius", filter: "Toyota" },
  { value: "RAV4", label: "RAV4", filter: "Toyota" },
  { value: "Sequoia", label: "Sequoia", filter: "Toyota" },
  { value: "Sienna", label: "Sienna", filter: "Toyota" },
  { value: "Tacoma", label: "Tacoma", filter: "Toyota" },
  { value: "Tundra", label: "Tundra", filter: "Toyota" },
  // Volkswagen
  { value: "Atlas", label: "Atlas", filter: "Volkswagen" },
  { value: "Beetle", label: "Beetle", filter: "Volkswagen" },
  { value: "Golf", label: "Golf", filter: "Volkswagen" },
  { value: "Jetta", label: "Jetta", filter: "Volkswagen" },
  { value: "Passat", label: "Passat", filter: "Volkswagen" },
  { value: "Tiguan", label: "Tiguan", filter: "Volkswagen" }
];
